<a href="https://colab.research.google.com/github/Carl-Zzdr/MLstudy/blob/main/HW%EF%BC%8D241027%EF%BC%8D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1. 读取数据集
import pickle
import numpy as np

# 定义故障类型
faults = [
    '12DriveEndFault0.007-Ball_211',
    '12DriveEndFault0.007-InnerRace_214',
    '12DriveEndFault0.007-OuterRace6_217',
    '12DriveEndFault0.014-InnerRace_225',
    '12DriveEndFault0.021-InnerRace_226'
]

# 加载数据
dataset = []
for fault in faults:
    path = '/content/drive/MyDrive/GZdata/' + fault + '.pkl'  # 修改路径
    with open(path, 'rb') as f:
        data = pickle.load(f)
    dataset.extend(data)

# 转换为数组格式
dataset_x = np.array(dataset)
label_y = np.array([0]*600 + [1]*600 + [2]*600 + [3]*600 + [4]*600)

# 2. 划分训练和测试集
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset_x, label_y, test_size=0.3, random_state=42)

# 3. 将数据集转换为Tensor并构建神经网络
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense

# 定义神经网络结构
img_shape = (1024,)
in_image = Input(shape=img_shape)

# 构建多层全连接神经网络
g = Dense(2048, activation='sigmoid')(in_image)
g = Dense(1024, activation='sigmoid')(g)
g = Dense(512, activation='sigmoid')(g)
g = Dense(256, activation='sigmoid')(g)
g = Dense(128, activation='sigmoid')(g)
out = Dense(64, activation='softmax')(g)

# 编译模型
NN_model = tf.keras.models.Model(inputs=in_image, outputs=out)
NN_model.summary()

# 提取特征
X_train_features = NN_model.predict(X_train)
X_test_features = NN_model.predict(X_test)

# 4. 逻辑回归分类器
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 创建并训练逻辑回归模型，运行100次迭代
log_reg = LogisticRegression(max_iter=100)
log_reg.fit(X_train_features, y_train)

# 使用模型进行预测
y_pred = log_reg.predict(X_test_features)

# 5. 输出分类结果
acc = accuracy_score(y_test, y_pred)
print('Logistic Regression Accuracy:', acc)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)           │ (None, 1024)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 2048)                │       2,099,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 1024)                │       2,098,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 512)                 │         524,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 64)                  │           8,256 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,894,656 (18.67 MB)

 Trainable params: 4,894,656 (18.67 MB)

 Non-trainable params: 0 (0.00 B)

66/66 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step
29/29 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
Logistic Regression Accuracy: 0.17666666666666667
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       197
           1       0.00      0.00      0.00       173
           2       0.00      0.00      0.00       186
           3       0.18      1.00      0.30       159
           4       0.00      0.00      0.00       185

    accuracy                           0.18       900
   macro avg       0.04      0.20      0.06       900
weighted avg       0.03      0.18      0.05       900

[[  0   0   0 197   0]
 [  0   0   0 173   0]
 [  0   0   0 186   0]
 [  0   0   0 159   0]
 [  0   0   0 185   0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
